ffs
sound wasnt working and i didnt realize

diff --git a/SOURCE/q/qcomp b/SOURCE/q/qcomp
--- a/SOURCE/q/qcomp
+++ b/SOURCE/q/qcomp
@@ -1,44 +1,27 @@
 #!/bin/sh
 
 echo -e "\e[93m(not as fake) qcomp\e[0m"
-
 # no args
-if [ $# -eq 0 ]; then
-	echo -e "usage: qcomp [folder]\n"
-	exit 1
-fi
-# non existent dir arg
-if [ ! -d "$1" ]; then
-	echo invalid path
-	exit 1
-fi
-indir=$1
-find=/usr/bin/find
+[ $# -eq 0 ] && { echo -e "usage: qcomp [folder]"; exit 1; }
+# non existent input dir arg
+[ ! -d "$1" ] && { echo "invalid path"; exit 1; }
+indir=$1; find=/usr/bin/find
 # >:(
 
-# manual output
-if [ -z "$2" ]; then
-	outdir=$1_build/
-else
-	outdir=$2/
-fi
-if	[ ! "$(dirname "$0")" = "." ]; then
-	bin=$(realpath "$0")/ # ???
-else
-	bin=$(which "$0")/ # required when script is pathed
-fi
+# check for manually specified output
+[ -z "$2" ] && outdir="$1_build/" || outdir="$2/"
+[ ! "$(dirname "$0")" = "." ] && bin="$(realpath "$0")/" || bin="$(which "$0")/"
+								#???						# required when script is pathed
+#thx luke / https://stackoverflow.com/a/21913843
 
-bin=$(dirname "$bin")
-wbin=$(cygpath -w "$bin")
-NL=$'\n'
-nul=/dev/null
-
+bin=$(dirname "$bin"); wbin=$(cygpath -w "$bin"); NL=$'\n'; nul=/dev/null
 echo -e "\e[33m*****  Q COMPILATION   *****\e[0m"
 
 INPUTS=$(pushd "$indir" > $nul && $find * -type f -name "*.q" && popd > $nul)
 for f in $INPUTS
 do
 	out="$outdir${f%%.*}.qb.xen"
+	# (re)compile files after being modified / or if they're new
 	if [ ! -f "$out" ] || [ "$out" -ot "$indir/$f" ]; then
 		mkdir -p "${outdir}$(dirname $f)"
 		echo -e "\e[97mCompiling $f...\e[0m"
